use cent-Os and yum

diff --git a/hadoop/bin/start-hadoop b/hadoop/bin/start-hadoop
--- a/hadoop/bin/start-hadoop
+++ b/hadoop/bin/start-hadoop
@@ -3,31 +3,16 @@
 echo "run start-hadoop"
 
 # Check user environment variable
-if [[ -z "${HDFS_USER}" ]]; then
-  echo "Missing HDFS_USER environment variable" >&2
+if [[ -z "${HADOOP_USER}" ]]; then
+  echo "Missing HADOOP_USER environment variable" >&2
   exit 1
 fi
-if [[ -z "${HDFS_GROUP}" ]]; then
-  echo "Missing HDFS_GROUP environment variable" >&2
-  echo "Using default HDFS_GROUP as HDFS_USER" >&2
-  export HDFS_GROUP=$HDFS_USER
-fi
-# Set HADOOP_USER_NAME environment vairable
-HADOOP_USER_NAME="${HDFS_USER}"
-echo "export  HADOOP_USER_NAME=\"${HDFS_USER}\"" >> /etc/bash.bashrc
-# Create user for HDFS
-adduser --disabled-password --gecos "" $HDFS_USER
-groupadd $HDFS_GROUP
-usermod -a -G $HDFS_GROUP $HDFS_USER
-# Fix directory permissions
-chown -R $HDFS_USER:$HDFS_GROUP /opt/util/app
-chown -R $HDFS_USER:$HDFS_GROUP /opt/hdfs
-chown -R $HDFS_USER:$HDFS_GROUP $HADOOP_HOME
+
 # Select node type
 if [[ "${1}" = 'namenode' ]]; then
-  su $HDFS_USER -c "/opt/util/bin/start-hadoop-namenode $2"
+  su $HADOOP_USER -c "/opt/util/bin/start-hadoop-namenode $2"
 elif [[ "${1}" =  'datanode' ]]; then
-  su $HDFS_USER -c "/opt/util/bin/start-hadoop-datanode $2 $3"
+  su $HADOOP_USER -c "/opt/util/bin/start-hadoop-datanode $2 $3"
 else
   echo "Invalid command '${1}'" >&2
   exit 1
